title: The Settle Project
author: Brett Settle
email: brettjsettle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An online résumé for Brett Settle, developed to showcase projects, work experience, and
  anything else worth documenting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thesettleproject.com" # the base hostname & protocol for your site, e.g. http://example.com

footer-links:
  dribbble:
  facebook: brett.settle.5
  flickr: 152867215@N08
  github: brettjsettle
  instagram:
  linkedin: brettjsettle
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: u/0/108626658789572132923

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: brettjsettle

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Build settings
markdown: kramdown
#theme: jekyll-theme-minimal

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

plugins:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - draft
