title: The Settle Project
name: Brett Settle
email: brettjsettle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An online résumé for Brett Settle, developed to showcase projects, work experience, and
  anything else worth documenting.  The Settle Project was created after I graduated from UCI in 2017.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://thesettleproject.com" # the base hostname & protocol for your site, e.g. http://example.com
username:  brettjsettle

paginate: 5
paginate_path: "blog/page:num/"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - draft
